backend:
  name: github
  repo: cwmyers/joannamyers.org
  branch: main

locale: en
site_url: https://www.joannamyers.org
logo_url: https://www.joannamyers.org/favicon.svg

media_folder: src/images
public_folder: /images

collections:
  - name: posts
    label: Blog Posts
    label_singular: Post
    folder: src/posts
    create: true
    format: yaml-frontmatter
    extension: md
    slug: "{{fields.title | slugify}}"
    summary: "{{title}} — {{date | date('DD MMM YYYY')}}"
    sortable_fields: [date, title]
    fields:
      - label: Title
        name: title
        widget: string
      - label: Publish date
        name: date
        widget: datetime
        date_format: YYYY-MM-DD
        time_format: false
        format: YYYY-MM-DD
        default_date: "{{now}}"
        required: false
      - label: Categories
        name: tags
        widget: list
        required: false
        add_label: Add category
        default: []
      - label: Body
        name: body
        widget: markdown

  - name: pages
    label: Pages
    files:
      - label: About page
        name: about
        file: src/about.md
        fields:
          - label: Body
            name: body
            widget: markdown
